//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarjaAEP.wsFdm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://saam.com/webservices/", ConfigurationName="wsFdm.FdmSoap")]
    public interface FdmSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetDocTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetDocTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetDocTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetDocTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetDocTypesByCompany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetDocTypesByCompany(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetDocTypesByCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetDocTypesByCompanyAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetDocTypesByUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetDocTypesByUser(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetDocTypesByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetDocTypesByUserAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/UrlFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UrlFile(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/UrlFile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UrlFileAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/UrlsFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UrlsFile(string strRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/UrlsFile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UrlsFileAsync(string strRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/IdArchivos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode IdArchivos(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/IdArchivos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> IdArchivosAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/Archivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Archivo(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/Archivo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ArchivoAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/ValDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ValDoc(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/ValDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ValDocAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/ValSimple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ValSimple(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/ValSimple", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ValSimpleAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/InsDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode InsDoc(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/InsDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> InsDocAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/DelDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode DelDoc(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/DelDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DelDocAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetCompanies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCompanies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetCompanies", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCompaniesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetSystems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetSystems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetSystems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetSystemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetLocations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/GetLocations", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/ValLogIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ValLogIn(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/ValLogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ValLogInAsync(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/UpdUsrPas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdUsrPas(System.Xml.XmlNode xmlRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://saam.com/webservices/UpdUsrPas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdUsrPasAsync(System.Xml.XmlNode xmlRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FdmSoapChannel : TarjaAEP.wsFdm.FdmSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FdmSoapClient : System.ServiceModel.ClientBase<TarjaAEP.wsFdm.FdmSoap>, TarjaAEP.wsFdm.FdmSoap {
        
        public FdmSoapClient() {
        }
        
        public FdmSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FdmSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FdmSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FdmSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GetDocTypes() {
            return base.Channel.GetDocTypes();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetDocTypesAsync() {
            return base.Channel.GetDocTypesAsync();
        }
        
        public System.Xml.XmlNode GetDocTypesByCompany(System.Xml.XmlNode xmlRequest) {
            return base.Channel.GetDocTypesByCompany(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetDocTypesByCompanyAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.GetDocTypesByCompanyAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode GetDocTypesByUser(System.Xml.XmlNode xmlRequest) {
            return base.Channel.GetDocTypesByUser(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetDocTypesByUserAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.GetDocTypesByUserAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode UrlFile(System.Xml.XmlNode xmlRequest) {
            return base.Channel.UrlFile(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UrlFileAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.UrlFileAsync(xmlRequest);
        }
        
        public string UrlsFile(string strRequest) {
            return base.Channel.UrlsFile(strRequest);
        }
        
        public System.Threading.Tasks.Task<string> UrlsFileAsync(string strRequest) {
            return base.Channel.UrlsFileAsync(strRequest);
        }
        
        public System.Xml.XmlNode IdArchivos(System.Xml.XmlNode xmlRequest) {
            return base.Channel.IdArchivos(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> IdArchivosAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.IdArchivosAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode Archivo(System.Xml.XmlNode xmlRequest) {
            return base.Channel.Archivo(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ArchivoAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.ArchivoAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode ValDoc(System.Xml.XmlNode xmlRequest) {
            return base.Channel.ValDoc(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ValDocAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.ValDocAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode ValSimple(System.Xml.XmlNode xmlRequest) {
            return base.Channel.ValSimple(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ValSimpleAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.ValSimpleAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode InsDoc(System.Xml.XmlNode xmlRequest) {
            return base.Channel.InsDoc(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> InsDocAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.InsDocAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode DelDoc(System.Xml.XmlNode xmlRequest) {
            return base.Channel.DelDoc(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DelDocAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.DelDocAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode GetCompanies() {
            return base.Channel.GetCompanies();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCompaniesAsync() {
            return base.Channel.GetCompaniesAsync();
        }
        
        public System.Xml.XmlNode GetSystems() {
            return base.Channel.GetSystems();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetSystemsAsync() {
            return base.Channel.GetSystemsAsync();
        }
        
        public System.Xml.XmlNode GetLocations() {
            return base.Channel.GetLocations();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLocationsAsync() {
            return base.Channel.GetLocationsAsync();
        }
        
        public System.Xml.XmlNode ValLogIn(System.Xml.XmlNode xmlRequest) {
            return base.Channel.ValLogIn(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ValLogInAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.ValLogInAsync(xmlRequest);
        }
        
        public System.Xml.XmlNode UpdUsrPas(System.Xml.XmlNode xmlRequest) {
            return base.Channel.UpdUsrPas(xmlRequest);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdUsrPasAsync(System.Xml.XmlNode xmlRequest) {
            return base.Channel.UpdUsrPasAsync(xmlRequest);
        }
    }
}
